var gridpreset_classic = [
    [
        "Bow",
        "Hookshot",
        "Hammer",
        "Bombs",
        "Bombchus",
        "Scale",
        "Gloves",
    ],
    [
        "Kokiri Sword",
        "Biggoron Sword",
        "Mirror Shield",
        "Zora Tunic",
        "Goron Tunic",
        "Iron Boots",
        "Hover Boots",
    ],
    [
        "Dins Fire",
        "Nayrus Love",
        "Farores Wind",
        "Magic Meter",
        "Fire Arrows",
        "Ice Arrows",
        "Light Arrows",
    ],
    [
        "Slingshot",
        "Boomerang",
        "Lens of Truth",
        "Ocarina",
        "Bottle",
        "Bottle with Letter",
        "Magic Bean",
    ],
    [
        "Wallet",
        "Gold Skulltula Token",
        "Child Trade",
        "Adult Trade",
        "Gerudo Membership Card",
    ],
    [
        "Zeldas Lullaby",
        "Eponas Song",
        "Suns Song",
        "Sarias Song",
        "Song of Time",
        "Song of Storms",
    ],
    [
        "Minuet of Forest",
        "Bolero of Fire",
        "Serenade of Water",
        "Nocturne of Shadow",
        "Requiem of Spirit",
        "Prelude of Light",
    ],
    [
        "Forest Medallion",
        "Fire Medallion",
        "Water Medallion",
        "Shadow Medallion",
        "Spirit Medallion",
        "Light Medallion",
    ],
    [
        "Kokiri Emerald",
        "Goron Ruby",
        "Zora Sapphire",
    ]
]

var gridpreset_natural = [
    [
        "Deku Sticks",
        "Deku Nuts",
        "Bombs",
        "Bow",
        "Fire Arrows",
        "Dins Fire",
    ],
    [
        "Slingshot",
        "Ocarina",
        "Bombchus",
        "Hookshot",
        "Ice Arrows",
        "Nayrus Love",
    ],
    [
        "Boomerang",
        "Lens of Truth",
        "Magic Bean",
        "Hammer",
        "Light Arrows",
		"Farores Wind",
    ],
    [
        "Bottle",
        "Bottle with Letter",
		"Piece of Heart",
		"Heart Container",
        "Child Trade",
        "Adult Trade",
	],
    [
        "Kokiri Sword",
        "Master Sword",
        "Biggoron Sword",
        "Deku Shield",
        "Hylian Shield",
        "Mirror Shield",
	],
    [
        "Gloves",
        "Scale",
        "Goron Tunic",
        "Zora Tunic",
        "Iron Boots",
        "Hover Boots",
	],
    [
        "Zeldas Lullaby",
        "Eponas Song",
        "Suns Song",
        "Sarias Song",
        "Song of Time",
        "Song of Storms",
    ],
    [
        "Minuet of Forest",
        "Bolero of Fire",
        "Serenade of Water",
        "Nocturne of Shadow",
        "Requiem of Spirit",
        "Prelude of Light",
    ],
    [
        "Forest Medallion",
        "Fire Medallion",
        "Water Medallion",
        "Shadow Medallion",
        "Spirit Medallion",
        "Light Medallion",
    ],
    [
        "Kokiri Emerald",
        "Goron Ruby",
        "Zora Sapphire",
        "Wallet",
        "Gerudo Membership Card",
        "Gold Skulltula Token",
    ]
]